### ISSUE TITLE
Sapeon

### ISSUE THREAD

**Issue by aolofsson** [aolofsson/awesome-semiconductor-startups#95]
https://m.koreatimes.co.kr/pages/article.asp?newsIdx=380797

**Comment by afaerber** [comment]
@aolofsson Are you sure about dropping Sapeon and leaving Rebellions? [sapeon.com](https://www.sapeon.com/) translated by Google seems to indicate the inverse:

> [...] the Company will be the surviving company and Rebellion Co., Ltd. (hereinafter referred to as "Rebellion") will be the extinguished company [...] (merger date: November 1, 2024). In accordance with the above merger, the Company will comprehensively succeed to all rights and obligations of Rebellion, and Rebellion will be extinguished.
